import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import NavBar from '@/components/Layout/NavBar/NavBar';
import Footer from '@/components/Layout/Footer/Footer';
import StoreProvider from '@/lib/StoreProvider';
import { Toaster } from 'sonner';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Best_group_e-commerce',
  description: 'Generated by amazing team',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} 
        antialiased dark:bg-dark-theme-bg 
        min-h-screen flex flex-col `}
      >
        <StoreProvider>
          <Toaster
            richColors
            position="top-center"
            duration={4000}
            toastOptions={{
              style: {
                background: 'var(--color-light-theme-btn-product-bg)',
                border: 'var(--color-light-theme-border-color)',
                color: '#fff',
                fontWeight: 'bold',
                fontSize: '16px',
                borderRadius: '12px',
                padding: '12px 24px',
                boxShadow: '0 4px 12px rgba(0,0,0,0.3)',
              },
            }}
          />
          <div
            className="sticky bg-white top-0 z-50 w-full 
          border-b border-light-theme-border-color dark:border-dark-theme-border-color dark:bg-dark-theme-bg "
          >
            <div className="max-w-[1920px] mx-auto">
              <NavBar />
            </div>
          </div>
          <main className="flex-grow max-w-[1200px] mx-auto w-full">
            {children}
          </main>
          <div
            className="w-full
          border-t border-light-theme-border-color dark:border-dark-theme-border-color dark:bg-dark-theme-bg"
          >
            <div className="max-w-[1200px] mx-auto">
              <Footer />
            </div>
          </div>
        </StoreProvider>
      </body>
    </html>
  );
}
