export const slides = [
  {
    itemId: 'apple-iphone-14-512gb-midnight',
    text: 'Now available',
    subText: 'in our store!',
    slogan: 'Be the first!',
    product: 'iPhone 14 Pro',
    productSlogan: 'Pro. Beyond.',
    image: '/img/Carousel/category-phones.png',
    modelUrl: '/models/iPhone14Pro.glb',
  },
  {
    itemId: 'apple-ipad-pro-11-2021-2tb-spacegray',
    text: 'Apple iPad Pro 11',
    subText: 'in our store!',
    slogan: 'Limited Edition!',
    product: 'iPad Air',
    productSlogan: 'Unfold Creativity.',
    image: '/img/Carousel/ipad.png',
  },
  {
    itemId: '',
    text: 'Now available',
    subText: 'in our store!',
    slogan: 'Exclusive Watch!',
    product: 'Apple Watch Ultra',
    productSlogan: 'Time to Shine.',
    image: '/img/Carousel/apple-watch.png',
  },
];
